// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/pixelforging.proto

package pixelforging_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WakeMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeMsg) Reset() {
	*x = WakeMsg{}
	mi := &file_proto_pixelforging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeMsg) ProtoMessage() {}

func (x *WakeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pixelforging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeMsg.ProtoReflect.Descriptor instead.
func (*WakeMsg) Descriptor() ([]byte, []int) {
	return file_proto_pixelforging_proto_rawDescGZIP(), []int{0}
}

type UpMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Up            string                 `protobuf:"bytes,1,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpMsg) Reset() {
	*x = UpMsg{}
	mi := &file_proto_pixelforging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpMsg) ProtoMessage() {}

func (x *UpMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pixelforging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpMsg.ProtoReflect.Descriptor instead.
func (*UpMsg) Descriptor() ([]byte, []int) {
	return file_proto_pixelforging_proto_rawDescGZIP(), []int{1}
}

func (x *UpMsg) GetUp() string {
	if x != nil {
		return x.Up
	}
	return ""
}

type ExtractPaletteInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FileBytes []byte                 `protobuf:"bytes,1,opt,name=fileBytes,proto3" json:"fileBytes,omitempty"`
	FileName  string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileType  string                 `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	// The following fields are optional and can be set to 0 if not needed
	// The following fields configure shape of the palette
	ColorsPerRow  int32 `protobuf:"varint,4,opt,name=colorsPerRow,proto3" json:"colorsPerRow,omitempty"`
	ColorWidth    int32 `protobuf:"varint,5,opt,name=colorWidth,proto3" json:"colorWidth,omitempty"`
	ColorHeight   int32 `protobuf:"varint,6,opt,name=colorHeight,proto3" json:"colorHeight,omitempty"`
	ColorNum      int32 `protobuf:"varint,7,opt,name=colorNum,proto3" json:"colorNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractPaletteInput) Reset() {
	*x = ExtractPaletteInput{}
	mi := &file_proto_pixelforging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractPaletteInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractPaletteInput) ProtoMessage() {}

func (x *ExtractPaletteInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pixelforging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractPaletteInput.ProtoReflect.Descriptor instead.
func (*ExtractPaletteInput) Descriptor() ([]byte, []int) {
	return file_proto_pixelforging_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractPaletteInput) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

func (x *ExtractPaletteInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExtractPaletteInput) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ExtractPaletteInput) GetColorsPerRow() int32 {
	if x != nil {
		return x.ColorsPerRow
	}
	return 0
}

func (x *ExtractPaletteInput) GetColorWidth() int32 {
	if x != nil {
		return x.ColorWidth
	}
	return 0
}

func (x *ExtractPaletteInput) GetColorHeight() int32 {
	if x != nil {
		return x.ColorHeight
	}
	return 0
}

func (x *ExtractPaletteInput) GetColorNum() int32 {
	if x != nil {
		return x.ColorNum
	}
	return 0
}

type ExtractPaletteOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaletteBytes  []byte                 `protobuf:"bytes,1,opt,name=paletteBytes,proto3" json:"paletteBytes,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractPaletteOutput) Reset() {
	*x = ExtractPaletteOutput{}
	mi := &file_proto_pixelforging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractPaletteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractPaletteOutput) ProtoMessage() {}

func (x *ExtractPaletteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pixelforging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractPaletteOutput.ProtoReflect.Descriptor instead.
func (*ExtractPaletteOutput) Descriptor() ([]byte, []int) {
	return file_proto_pixelforging_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractPaletteOutput) GetPaletteBytes() []byte {
	if x != nil {
		return x.PaletteBytes
	}
	return nil
}

func (x *ExtractPaletteOutput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExtractPaletteOutput) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

var File_proto_pixelforging_proto protoreflect.FileDescriptor

const file_proto_pixelforging_proto_rawDesc = "" +
	"\n" +
	"\x18proto/pixelforging.proto\x12\x11pixelforging_grpc\"\t\n" +
	"\aWakeMsg\"\x17\n" +
	"\x05UpMsg\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\tR\x02up\"\xed\x01\n" +
	"\x13ExtractPaletteInput\x12\x1c\n" +
	"\tfileBytes\x18\x01 \x01(\fR\tfileBytes\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileType\x18\x03 \x01(\tR\bfileType\x12\"\n" +
	"\fcolorsPerRow\x18\x04 \x01(\x05R\fcolorsPerRow\x12\x1e\n" +
	"\n" +
	"colorWidth\x18\x05 \x01(\x05R\n" +
	"colorWidth\x12 \n" +
	"\vcolorHeight\x18\x06 \x01(\x05R\vcolorHeight\x12\x1a\n" +
	"\bcolorNum\x18\a \x01(\x05R\bcolorNum\"r\n" +
	"\x14ExtractPaletteOutput\x12\"\n" +
	"\fpaletteBytes\x18\x01 \x01(\fR\fpaletteBytes\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileType\x18\x03 \x01(\tR\bfileType2\xb3\x01\n" +
	"\fPixelForging\x12e\n" +
	"\x0eExtractPalette\x12&.pixelforging_grpc.ExtractPaletteInput\x1a'.pixelforging_grpc.ExtractPaletteOutput(\x010\x01\x12<\n" +
	"\x04Wake\x12\x1a.pixelforging_grpc.WakeMsg\x1a\x18.pixelforging_grpc.UpMsgB$Z\"./src/backend/pb/pixelforging-grpcb\x06proto3"

var (
	file_proto_pixelforging_proto_rawDescOnce sync.Once
	file_proto_pixelforging_proto_rawDescData []byte
)

func file_proto_pixelforging_proto_rawDescGZIP() []byte {
	file_proto_pixelforging_proto_rawDescOnce.Do(func() {
		file_proto_pixelforging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pixelforging_proto_rawDesc), len(file_proto_pixelforging_proto_rawDesc)))
	})
	return file_proto_pixelforging_proto_rawDescData
}

var file_proto_pixelforging_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_pixelforging_proto_goTypes = []any{
	(*WakeMsg)(nil),              // 0: pixelforging_grpc.WakeMsg
	(*UpMsg)(nil),                // 1: pixelforging_grpc.UpMsg
	(*ExtractPaletteInput)(nil),  // 2: pixelforging_grpc.ExtractPaletteInput
	(*ExtractPaletteOutput)(nil), // 3: pixelforging_grpc.ExtractPaletteOutput
}
var file_proto_pixelforging_proto_depIdxs = []int32{
	2, // 0: pixelforging_grpc.PixelForging.ExtractPalette:input_type -> pixelforging_grpc.ExtractPaletteInput
	0, // 1: pixelforging_grpc.PixelForging.Wake:input_type -> pixelforging_grpc.WakeMsg
	3, // 2: pixelforging_grpc.PixelForging.ExtractPalette:output_type -> pixelforging_grpc.ExtractPaletteOutput
	1, // 3: pixelforging_grpc.PixelForging.Wake:output_type -> pixelforging_grpc.UpMsg
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pixelforging_proto_init() }
func file_proto_pixelforging_proto_init() {
	if File_proto_pixelforging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pixelforging_proto_rawDesc), len(file_proto_pixelforging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pixelforging_proto_goTypes,
		DependencyIndexes: file_proto_pixelforging_proto_depIdxs,
		MessageInfos:      file_proto_pixelforging_proto_msgTypes,
	}.Build()
	File_proto_pixelforging_proto = out.File
	file_proto_pixelforging_proto_goTypes = nil
	file_proto_pixelforging_proto_depIdxs = nil
}
