# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pixelforging.proto

require 'google/protobuf'


descriptor_data = "\n\x18proto/pixelforging.proto\x12\x11pixelforging_grpc\"\x9d\x01\n\x13\x45xtractPaletteInput\x12\x11\n\tfileBytes\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ileType\x18\x03 \x01(\t\x12\x14\n\x0c\x63olorsPerRow\x18\x04 \x01(\x05\x12\x12\n\ncolorWidth\x18\x05 \x01(\x05\x12\x13\n\x0b\x63olorHeight\x18\x06 \x01(\x05\x12\x10\n\x08\x63olorNum\x18\x07 \x01(\x05\"P\n\x14\x45xtractPaletteOutput\x12\x14\n\x0cpaletteBytes\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x10\n\x08\x66ileType\x18\x03 \x01(\t2u\n\x0cPixelForging\x12\x65\n\x0e\x45xtractPalette\x12&.pixelforging_grpc.ExtractPaletteInput\x1a\'.pixelforging_grpc.ExtractPaletteOutput(\x01\x30\x01\x42$Z\"./src/backend/pb/pixelforging-grpcb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module PixelforgingGrpc
  ExtractPaletteInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pixelforging_grpc.ExtractPaletteInput").msgclass
  ExtractPaletteOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pixelforging_grpc.ExtractPaletteOutput").msgclass
end
