# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pixelforging.proto for package 'pixelforging_grpc'

require 'grpc'
require 'pixelforging_pb'

module PixelforgingGrpc
  module PixelForging
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pixelforging_grpc.PixelForging'

      rpc :ExtractPalette, stream(::PixelforgingGrpc::ExtractPaletteInput), stream(::PixelforgingGrpc::ExtractPaletteOutput)
    end

    Stub = Service.rpc_stub_class
  end
end
